In [1]:
import numpy as np
import pandas as pd

In [6]:
sms_data = pd.read_csv('spam.csv', encoding = 'latin-1')

In [10]:
sms_data.drop(labels = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis = 1, inplace=True)

In [11]:
sms_data.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [30]:
import re
import nltk 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [33]:
stemming = PorterStemmer()
corpus = []

for i in range (0,len(sms_data)):
  s1 = re.sub('[^a-zA-Z]',repl = ' ',string = sms_data['v2'][i])
  s1.lower()
  s1 = s1.split()
  s1 = [stemming.stem(word) for word in s1 if word not in set(stopwords.words('english'))]
  s1 = ' '.join(s1)
  corpus.append(s1)

corpus[1]

'Ok lar joke wif u oni'

In [34]:
corpus[2]

'free entri wkli comp win FA cup final tkt st may text FA receiv entri question std txt rate T C appli'

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = TfidfVectorizer

In [50]:
x = CountVectorizer().fit_transform(corpus).toarray()

In [51]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [52]:
y = sms_data['v1'].values

In [53]:
y

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype=object)

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100, stratify = y)

In [56]:
X_train.shape

(3900, 6304)

In [58]:
X_test.shape

(1672, 6304)

In [59]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [60]:
y_pred = nb.predict(X_test)

In [61]:
y_pred

array(['ham', 'ham', 'ham', ..., 'spam', 'ham', 'ham'], dtype='<U4')

In [62]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [65]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n         ham       0.99      0.98      0.99      1448\n        spam       0.91      0.95      0.93       224\n\n    accuracy                           0.98      1672\n   macro avg       0.95      0.97      0.96      1672\nweighted avg       0.98      0.98      0.98      1672\n'

In [66]:
accuracy_score(y_test, y_pred)

0.9802631578947368

In [73]:
from sklearn.svm import LinearSVC
linearsvc = LinearSVC()
linearsvc.fit(X_train,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [75]:
y_pred = linearsvc.predict(X_test)

In [76]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n         ham       0.98      1.00      0.99      1448\n        spam       0.99      0.89      0.93       224\n\n    accuracy                           0.98      1672\n   macro avg       0.98      0.94      0.96      1672\nweighted avg       0.98      0.98      0.98      1672\n'

In [77]:
accuracy_score(y_test, y_pred)

0.9832535885167464